name: "Update CI Docker Image"

on:
  push:
    paths:
    - "ci/**"

jobs:
  build:
    name: "Update CI Docker Image"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Build Image"
      run: "docker build -t neqo-ci ci"

    - name: "Publish Latest"
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
        docker push neqoquic/ci:latest

    - name: "Publish Tag"
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
        ref=${{ github.ref }}
        docker push "neqoquic/ci:${ref#refs/tags/}"
